### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Radamel** [duconstp/Tetris#23]
600 mb de mémoire utilisés par le process chrome en fin de partie (200+ points), contre 150 mb au début. (mode Candy HD 1080p60)

**Comment by PandaChauve** [comment]
resultat des dernières améliorations :

Avant en candyhd: 
30 mo par partie lancée
croissance rapide en cours de partie (700 points en sandbox = 800mo)

Maintenant:
5mo par partie max
croissance lente en partie (1000 points sandbox 85mo)
