### ISSUE TITLE
Sharp fonts aka The WTF issue

### ISSUE THREAD

**Issue by Radamel** [duconstp/Tetris#24]
Comprendre pourquoi quand je joue au tetris, les polices de mon système deviennent "acérées", "pointues". Vu sur mon PC au boulot et celui à la maison. Il y a peut-être un raccourci clavier Windows qui se déclenche.

**Comment by PandaChauve** [comment]
Tu n'as pas un screenshot avant après ?

**Comment by Radamel** [comment]
Fait trop chaud pour fermer des issues.

**Comment by PandaChauve** [comment]
Fait trop chaud tout court

**Comment by Radamel** [comment]
Confirmé... c'est un bug dans mes yeux. Après une partie à 300 points en mode cube sur smartphone, j'ai l'impression que les polices sont cette fois arrondies !
