### ISSUE TITLE
Live display of apm

### ISSUE THREAD

**Issue by Radamel** [duconstp/Tetris#35]
Dans le panel de droite, afficher en temps réel le nombre d'apm = actions par minute (nombre de swaps + nombre de déplacements du swapper), c'est donc une vitesse !
- Ça peut vite monter, bon indicateur de dextérité
- Plus parlant que le simple total de swaps
- Donne un cachet pro gamer à la Warcraft/Starcraft 

Showstopper.

**Comment by PandaChauve** [comment]
done

**Comment by Radamel** [comment]
Génial Panda !
