### ISSUE TITLE
Avoid display of Angular template

### ISSUE THREAD

**Issue by Radamel** [duconstp/Tetris#55]
F5 sur la page > le template s'affiche brièvement avec le thème par défaut et les {{ }} d'Angular.

**Comment by PandaChauve** [comment]
set a cookie and hotswap the html server side (easy ...)

**Comment by PandaChauve** [comment]
Mwahahaha je l'ai fait en php, ça t'apprendra tien !!!!

header("Content-type: text/css; charset: UTF-8");
$theme = 'slate';
if(isset($_COOKIE['csstheme']) && ctype_alpha($_COOKIE['csstheme'])) //is set and is the current folder 
{
    $theme = strtolower($_COOKIE['csstheme']);
}
print file_get_contents($theme.".min.css");

**Comment by Radamel** [comment]
!empty c'est mieux que isset :p

**Comment by PandaChauve** [comment]
Pas specialement dans le cas présent.
