### ISSUE TITLE
[Android] Hide footer in game

### ISSUE THREAD

**Issue by Radamel** [duconstp/Tetris#83]
Le footer gâche de l'espace écran pourtant très limité sur mobile. In-game ça ne me semble vraiment pas utile...

**Comment by PandaChauve** [comment]
Lequel, parce qu'en théorie, le footer ne doit pas empiéter sur l'espace utile ?

**Comment by PandaChauve** [comment]
En plus c'est compliqué puisque le footer est sur toutes les pages

**Comment by PandaChauve** [comment]
Bon si je cache le footer ça ne change rien puisque ce sont les conteneurs qui contiennent les marges ....

je laisse tomber je vais casser trop de truc pour réussir et je ne suis pas convaincu ^^
