### ISSUE TITLE
Security hole in scores API 

### ISSUE THREAD

**Issue by Radamel** [duconstp/Tetris#85]
Y avait pas du chiffrement dans l'envoi des scores ? Ceci fonctionne :

POST:  /wwylApi/scores HTTP/1.1
Host: whenwillyoulose.com:1337
Connection: keep-alive
Content-Length: 37
Accept: application/json, text/plain, _/_
Origin: http://whenwillyoulose.com
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.130 Safari/537.36
Content-Type: application/json;charset=UTF-8
Referer: http://whenwillyoulose.com/
Accept-Encoding: gzip, deflate
Accept-Language: fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4

{"score":5000,"user":2,"map":"classic"}

**Comment by PandaChauve** [comment]
issue 52
