### ISSUE TITLE
Critical bug in scores

### ISSUE THREAD

**Issue by Radamel** [duconstp/Tetris#89]
Qu'est-ce qui se passe avec les scores ? Je viens de coller un 150 et un 200 avec le compte Karaboudjan, et c'est un score de 10 qui apparaît dans mon classement. 

Cette fois j'ai bien vidé les 2 caches de Firefox (preuve je n'ai plus le bug du thème pas chargé).

**Comment by PandaChauve** [comment]
Le bonheur de devoir inventer un mécanisme de cryptage inutile ^^

**Comment by PandaChauve** [comment]
ca devrait aller mieux
