### ISSUE TITLE
Pause bug still present

### ISSUE THREAD

**Issue by Radamel** [duconstp/Tetris#90]
Le chrono continue de défiler alors que le jeu est en pause. Vu plusieurs fois avec Firefox Developer. Impossible à reproduire... 

À essayer : j'ai l'impression d'avoir eu le bug quand j'ai mis la pause alors qu'un bloc en chute se trouvait encore avant la ligne rouge. Trop chiant à refaire, j'ai pas le réflexe, mais avec le code ça devrait être facile.

edit ^ c'est pas ça...

**Comment by PandaChauve** [comment]
essaye retry puis pause

**Comment by Radamel** [comment]
Ouais x)
